import { Injectable } from '@angular/core';
import { QuestionQuiz } from '../../model/interfaces/QuestionQuiz.model';

@Injectable({
  providedIn: 'root',
})
export class ReviewService {
  questions: QuestionQuiz[] = [
    {
      indexBadge: "01",
      difficulty: "Easy",
      answer:
        "The DOM (Document Object Model) is a tree-like representation of an HTML page, generated by the browser, that lets JavaScript read and modify the structure, content, and style of a page dynamically.",
      question: "What is the DOM and why is it important?"
    },
    {
      indexBadge: "02",
      difficulty: "Easy",
      answer:
        "Flexbox is a one-dimensional layout model for arranging items in a row or column, while CSS Grid is two-dimensional and lets you control both rows and columns at the same time. Flexbox fits component-level layout; Grid fits page-level layout.",
      question: "What's the difference between Flexbox and CSS Grid?"
    },
    {
      indexBadge: "03",
      difficulty: "Medium",
      answer:
        "Closures happen when a function remembers variables from its outer scope even after that outer function has returned. They're commonly used for data privacy, memoization, and creating factory functions.",
      question: "What is a closure in JavaScript?"
    },
    {
      indexBadge: "04",
      difficulty: "Easy",
      answer:
        "let and const are block-scoped and not hoisted the same way as var, which is function-scoped. const additionally prevents reassignment of the variable binding, though object contents can still change.",
      question: "What's the difference between let, const, and var?"
    },
    {
      indexBadge: "05",
      difficulty: "Medium",
      answer:
        "Event bubbling is when an event triggered on a child element propagates upward through its ancestors. Event capturing is the reverse: the event travels from the root down to the target before bubbling back up.",
      question: "Explain event bubbling and event capturing."
    },
    {
      indexBadge: "06",
      difficulty: "Medium",
      answer:
        "A Promise represents a value that may be available now, later, or never, with three states: pending, fulfilled, or rejected. async/await is syntactic sugar built on top of Promises that lets you write asynchronous code in a synchronous-looking style.",
      question: "What is a Promise and how does async/await relate to it?"
    },
    {
      indexBadge: "07",
      difficulty: "Easy",
      answer:
        "localStorage persists data with no expiration date, sessionStorage clears when the tab closes, and cookies are small pieces of data sent with every HTTP request and can carry an expiration date.",
      question:
        "What's the difference between localStorage, sessionStorage, and cookies?"
    },
    {
      indexBadge: "08",
      difficulty: "Hard",
      answer:
        "The virtual DOM is a lightweight in-memory copy of the real DOM. Frameworks like React compute the difference between the previous and new virtual DOM (diffing) and apply only the minimal set of real DOM updates, which improves performance.",
      question:
        "What is the virtual DOM and how does it improve performance?"
    },
    {
      indexBadge: "09",
      difficulty: "Medium",
      answer:
        "CSS specificity determines which rule wins when multiple selectors target the same element. It's calculated from four levels: inline styles, IDs, classes/attributes/pseudo-classes, and element/pseudo-elements, in that order of weight.",
      question: "How does CSS specificity work?"
    },
    {
      indexBadge: "10",
      difficulty: "Hard",
      answer:
        "Debouncing delays a function call until a pause in events occurs, which is useful for search inputs, while throttling ensures a function runs at most once every fixed interval, which is useful for scroll or resize handlers.",
      question: "What's the difference between debouncing and throttling?"
    },
    {
      indexBadge: "11",
      difficulty: "Medium",
      answer:
        "REST exposes fixed endpoints that return predefined data structures, often causing over- or under-fetching. GraphQL exposes a single endpoint where clients specify exactly the fields they need in one request.",
      question: "What's the difference between REST and GraphQL?"
    },
    {
      indexBadge: "12",
      difficulty: "Easy",
      answer:
        "Semantic HTML uses tags that describe their meaning, like <header>, <article>, and <nav>, rather than generic ones like <div>. It improves accessibility, SEO, and code readability.",
      question: "Why is semantic HTML important?"
    }
  ];


  getQuestionsQuiz() : QuestionQuiz[]{
    return this.questions;
  }

}
